=== cmmartti/verse-reader/public/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:hr="hymnalreader.net"
    targetNamespace="hymnalreader.net"
    elementFormDefault="qualified"
>
    <element name="hymnal">
        <complexType>
            <sequence>
                <element name="languages">
                    <complexType>
                        <sequence>
                            <element maxOccurs="unbounded" name="language">
                                <complexType>
                                    <attribute name="id" type="NCName" />
                                    <attribute name="name" type="string" use="required" />
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="indices" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="index" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="type" type="string" use="required" />
                                    <attribute name="name" type="string" use="required" />
                                    <attribute name="has-default-sort" type="boolean" />
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="contributors" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="contributor" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="id" type="NMTOKEN" />
                                    <attribute name="name" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="topics" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="topic" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="id" type="NMTOKEN" />
                                    <attribute name="name" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="origins" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="origin" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="id" type="NMTOKEN" />
                                    <attribute name="name" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="tunes" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="tune" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="id" type="NMTOKEN" />
                                    <attribute name="name" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="days" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="day" minOccurs="0" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="id" type="NMTOKEN" />
                                    <attribute name="name" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="pages">
                    <complexType>
                        <sequence>
                            <element name="page" type="hr:page" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="id" use="required" type="NCName" />
            <attribute name="language" use="required" type="NCName" />
            <attribute name="title" use="required" />
            <attribute name="year" use="required" type="integer" />
            <attribute name="publisher" />
        </complexType>
    </element>
    <complexType name="page">
        <sequence>
            <element name="contributor" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="type">
                        <simpleType>
                            <restriction base="NCName">
                                <enumeration value="author" />
                                <enumeration value="translator" />
                            </restriction>
                        </simpleType>
                    </attribute>
                    <attribute name="ref" type="NCName" />
                    <attribute name="year" type="string" use="optional"/>
                    <attribute name="note" type="string" use="optional"/>
                </complexType>
            </element>
            <element name="topic" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="ref" type="NCName" />
                </complexType>
            </element>
            <element name="origin" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="ref" type="NCName" />
                </complexType>
            </element>
            <element name="tune" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="ref" type="NCName" />
                </complexType>
            </element>
            <element name="day" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="ref" type="NCName" />
                    <attribute name="alternate" type="boolean"/>
                </complexType>
            </element>
            <element name="link" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <attribute name="book" type="string" use="required" />
                    <attribute name="edition" type="string" use="required" />
                    <attribute name="id" type="string" use="required" />
                </complexType>
            </element>
            <element name="title" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="verses" minOccurs="0">
                <complexType>
                    <sequence maxOccurs="unbounded">
                        <element name="verse" type="hr:verse-contents" minOccurs="1" maxOccurs="1"/>
                        <choice>
                            <element name="refrain" type="hr:verse-contents" minOccurs="0" maxOccurs="1"/>
                            <element name="chorus" type="hr:verse-contents" minOccurs="0" maxOccurs="1"/>
                        </choice>
                        <element name="verse" type="hr:verse-contents" minOccurs="0" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="language" type="NCName" default="en"/>
        <attribute name="id" use="required" type="positiveInteger"/>
        <attribute name="restricted" use="optional" type="boolean"/>
        <attribute name="deleted" use="optional" type="boolean"/>
    </complexType>
    <complexType name="verse-contents">
        <sequence>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="line" type="string" minOccurs="0" maxOccurs="unbounded" />
                <element name="repeat" minOccurs="0" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="line" type="string" maxOccurs="unbounded" />
                        </sequence>
                        <attribute name="times" default="2" type="positiveInteger" />
                    </complexType>
                </element>
            </choice>
        </sequence>
        <attribute name="deleted" use="optional" type="boolean"/>
    </complexType>
</schema>

=== cmmartti/verse-reader/public/sample.xml
<?xml version="1.0"?>
<hymnal
    xmlns="hymnalreader.net"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="hymnalreader.net schema.xsd"
    title="Christmas Carols"
    subtitle="Sample"
    year="2022"
    id="carols"
    language="en"
>
   <languages>
      <language id="en" name="English"/>
   </languages>
   <indices>
      <index type="topic" name="Topical Index" has-default-sort="true"/>
      <index type="tune" name="Index of Tunes"/>
      <index type="author" name="Index of Authors"/>
      <index type="translator" name="Index of Translators"/>
      <index type="origin" name="Index of Origins"/>
   </indices>
   <contributors>
      <contributor name="Unknown" id="unknown"/>
      <contributor name="Edmund Sears" id="edmund-sears"/>
      <contributor name="John Wesley Work Jr." id="john-wesley-work-jr"/>
      <contributor name="Katherine Kennicott Davis" id="katherine-kennicott-davis"/>
      <contributor name="Jester Hairston" id="jester-hairston"/>
      <contributor name="Phillips Brooks" id="phillips-brooks"/>
      <contributor name="Johnny Marks" id="johnny-marks"/>
      <contributor name="Jay Livingston" id="jay-livingston"/>
      <contributor name="Ray Evans" id="ray-evans"/>
      <contributor name="John Henry Hopkins Jr." id="john-henry-hopkins-jr" />
      <contributor name="Jean de Brébeuf" id="jean-de-brébeuf" />
      <contributor name="John Mason Neale" id="john-mason-neale" />
      <contributor name="St. Germanus I" id="st-germanus-i" />
      <contributor name="James Chadwick" id="james-chadwick" />
      <contributor name="James Montgomery" id="james-montgomery" />
      <contributor name="Wilfrid Moreau" id="wilfrid-moreau" />
      <contributor name="William Chatterton Dix" id="william-chatterton-dix" />
      <contributor name="Charles Wesley" id="charles-wesley" />
      <contributor name="William Sandys" id="william-sandys" />
      <contributor name="Isaac Watts" id="isaac-watts" />
      <contributor name="John Francis Wade" id="john-francis-wade" />
      <contributor name="Frederick Oakeley" id="frederick-oakeley" />
      <contributor name="Edward Caswall" id="edward-caswall" />
      <contributor name="Placide Cappeau" id="placide-cappeau" />
      <contributor name="John S. Dwight" id="john-s-dwight" />
      <contributor name="Joseph Mohr" id="joseph-mohr" />
      <contributor name="John Freeman Young" id="john-freeman-young" />
      <contributor name="Michael Perry" id="michael-perry" />
      <contributor name="Nahum Tate" id="nahum-tate" />
      <contributor name="Noël Regney" id="noël-regney" />
   </contributors>
   <topics>
      <topic name="Advent" id="advent" />
      <topic name="Christmas" id="christmas" />
      <topic name="Winter" id="winter" />
      <topic name="Epiphany" id="epiphany" />
   </topics>
   <origins>
      <origin id="austria" name="Austria"/>
      <origin id="canada" name="Canada"/>
      <origin id="england" name="England"/>
      <origin id="france" name="France"/>
      <origin id="latin" name="Latin"/>
      <origin id="greece" name="Greece"/>
      <origin id="usa" name="USA"/>
   </origins>
   <tunes>
      <tune name="Mueller" id="mueller"/>
      <tune name="Cradle Song" id="cradle-song"/>
      <tune name="Do you hear what I hear?" id="do-you-hear-what-i-hear"/>
      <tune name="Go Tell It on the Mountain" id="go-tell-it-on-the-mountain"/>
      <tune name="Jingle Bells" id="jingle-bells"/>
      <tune name="Carol" id="carol"/>
      <tune name="The Little Drummer Boy" id="little-drummer-boy"/>
      <tune name="Mary’s Boy Child" id="marys-boy-child"/>
      <tune name="St. Louis" id="st-louis"/>
      <tune name="Forest Green" id="forest-green"/>
      <tune name="Rudolph the red-nosed reindeer" id="rudolph-the-red-nosed-reindeer"/>
      <tune name="Silver Bells" id="silver-bells"/>
      <tune name="Three Kings of Orient" id="three-kings-of-orient"/>
      <tune name="Huron Carol" id="huron-carol"/>
      <tune name="Lo, how a rose e’er blooming" id="lo-how-a-rose-eer-blooming"/>
      <tune name="Regent Square" id="regent-square"/>
      <tune name="Calypso Carol" id="calypso-carol"/>
      <tune name="Coventry Carol" id="coventry-carol"/>
      <tune name="Tempus adest floridum" id="tempus-adest-floridum"/>
      <tune name="God Rest You Merry" id="god-rest-you-merry"/>
      <tune name="Mendelssohn" id="mendelssohn" />
      <tune name="I saw three ships" id="i-saw-three-ships" />
      <tune name="Antioch" id="antioch" />
      <tune name="Adeste Fideles" id="adeste-fideles" />
      <tune name="Cantique de Noel" id="cantique-de-noel" />
      <tune name="Greensleeves" id="greensleeves" />
      <tune name="Winchester Old" id="winchester-old" />
      <tune name="Christmas" id="christmas" />
      <tune name="Veni Emmanuel" id="veni-emmanuel" />
      <tune name="Dix" id="dix" />
   </tunes>
   <pages>
      <page id="1">
         <contributor type="author" ref="unknown"/>
         <topic ref="christmas"/>
         <origin ref="usa" />
         <tune ref="mueller"/>
         <tune ref="cradle-song"/>
         <title>Away in a manger, no crib for His bed</title>
         <verses>
            <verse>
               <line>Away in a manger, no crib for His bed,</line>
               <line>the little Lord Jesus lay down His sweet head:</line>
               <line>the stars in the sky looked down where He lay,</line>
               <line>the little Lord Jesus asleep on the hay.</line>
            </verse>
            <verse>
               <line>The cattle are lowing, the poor Baby wakes,</line>
               <line>but little Lord Jesus no crying He makes.</line>
               <line>I love Thee, Lord Jesus, look down from the sky,</line>
               <line>and stay by my cradle till morning is nigh.</line>
            </verse>
            <verse>
               <line>Be near me, Lord Jesus; I ask Thee to stay</line>
               <line>close by me forever, and love me, I pray.</line>
               <line>bless all the dear children in Thy tender care,</line>
               <line>and take us to Heaven, to live with Thee there.</line>
            </verse>
         </verses>
      </page>
      <page id="2">
         <contributor type="author" ref="noël-regney" />
         <topic ref="christmas"/>
         <origin ref="usa" />
         <tune ref="do-you-hear-what-i-hear" />
         <title>Do you hear what I hear?</title>
         <verses>
            <verse>
               <line>Said the night wind to the little lamb:</line>
               <line>“Do you see what I see?</line>
               <line>Way up in the sky, little lamb.</line>
               <line>Do you see what I see?</line>
               <line>A star, a star, dancing in the night</line>
               <repeat after=".”">
                  <line>with a tail as big as a kite</line>
               </repeat>
            </verse>
            <verse>
               <line>Said the little lamb to the shepherd boy:</line>
               <line>“Do you hear what I hear?</line>
               <line>Ringing through the sky, shepherd boy.</line>
               <line>Do you hear what I hear?</line>
               <line>A song, a song, high above the trees</line>
               <repeat after=".”">
                  <line>with a voice as big as the sea</line>
               </repeat>
            </verse>
            <verse>
               <line>Said the shepherd boy to the mighty king:</line>
               <line>“Do you know what I know?</line>
               <line>In your palace warm, mighty king.</line>
               <line>Do you know what I know?</line>
               <line>A Child, a Child shivers in the cold</line>
               <repeat after=".”">
                  <line>let us bring Him silver and gold</line>
               </repeat>
            </verse>
            <verse>
               <line>Said the king to the people everywhere:</line>
               <line>“Listen to what I say!</line>
               <line>Pray for peace, people everywhere!</line>
               <line>Listen to what I say!</line>
               <line>The Child, the Child, sleeping in the night</line>
               <repeat after=".”">
                  <line>He will bring us goodness and light</line>
               </repeat>
            </verse>
         </verses>
      </page>
      <page id="3">
         <contributor type="author" ref="john-wesley-work-jr" />
         <topic ref="christmas"/>
         <origin ref="usa" />
         <tune ref="go-tell-it-on-the-mountain" />
         <title>Go Tell It on the Mountain</title>
         <verses>
            <verse>
               <line>While shepherds kept their watching</line>
               <line>o’er silent flocks by night,</line>
               <line>behold, throughout the heavens</line>
               <line>there shone a holy light.</line>
            </verse>
            <chorus>
               <line>Go, tell it on the mountain,</line>
               <line>over the hills and everywhere;</line>
               <line>go, tell it on the mountain</line>
               <line>that Jesus Christ is born.</line>
            </chorus>
            <verse>
               <line>The shepherds feared and trembled</line>
               <line>when lo! above the earth</line>
               <line>rang out the angel chorus</line>
               <line>that hailed our Savior’s birth.</line>
            </verse>
            <verse>
               <line>Down in a lowly manger</line>
               <line>the humble Christ was born,</line>
               <line>and God sent us salvation</line>
               <line>that blessed Christmas morn.</line>
            </verse>
         </verses>
      </page>
      <page id="4">
         <contributor type="author" ref="edmund-sears" year="1849" />
         <topic ref="christmas"/>
         <origin ref="usa" />
         <tune ref="carol"/>
